"""agregar tabla producto_imagenes

Revision ID: 6e5605b00808
Revises: cc6fcd09cfb4
Create Date: 2026-05-03 21:56:54.216794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5605b00808'
down_revision: Union[str, Sequence[str], None] = 'cc6fcd09cfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_imagenes_id'), 'producto_imagenes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_imagenes_id'), table_name='producto_imagenes')
    op.drop_table('producto_imagenes')
    # ### end Alembic commands ###
