"""agregar_columna_activo_a_usuarios

Revision ID: 8e6739eb5b5e
Revises: 6e5605b00808
Create Date: 2026-05-12 15:01:44.790735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6739eb5b5e'
down_revision: Union[str, Sequence[str], None] = '6e5605b00808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'activo')
    # ### end Alembic commands ###
