"""eliminar_columna_activo

Revision ID: a8970be315d8
Revises: 8e6739eb5b5e
Create Date: 2026-05-12 16:28:52.719597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8970be315d8'
down_revision: Union[str, Sequence[str], None] = '8e6739eb5b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'activo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
